[project]
name = "pytorch-world"
version = "0.0.1"
description = "A Pytorch Based library for training world models"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gym>=0.26.2",
    "opencv-python>=4.12.0.88",
    "plotly>=6.5.0",
    "pre-commit>=4.5.0",
    "pygame>=2.6.1",
    "tensorboard>=2.20.0",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["setuptools>=61.0", "wheel", "build"]
build-backend = "setuptools.build_meta"
