[project]
name = "torchwm"
version = "0.2.1"
description = "A Modular Pytorch Based library for training world models"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ale-py>=0.11.2",
    "einops>=0.8.2",
    "fastapi>=0.116.0",
    "gym>=0.26.2",
    "gymnasium>=1.2.2",
    "mlagents-envs>=0.28.0",
    "moviepy>=2.2.1",
    "myst-parser>=5.0.0",
    "nbsphinx>=0.9.8",
    "opencv-python>=4.12.0.88",
    "plotly>=6.5.0",
    "pre-commit>=4.5.0",
    "pygame>=2.6.1",
    "pytest>=9.0.2",
    "pyyaml>=6.0.3",
    "sphinx>=9.1.0",
    "sphinx-autodoc-typehints>=3.6.2",
    "sphinx-copybutton>=0.5.2",
    "sphinx-rtd-theme>=3.1.0",
    "sphinxcontrib-bibtex>=2.6.5",
    "sphinxext-opengraph>=0.13.0",
    "tensorboard>=2.20.0",
    "tensorboardx>=2.6.4",
    "tqdm>=4.67.1",
    "uvicorn>=0.35.0",
]
license = "MIT"
keywords = ["world-models", "pytorch", "mbrl"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["setuptools>=61.0", "wheel", "build"]
build-backend = "setuptools.build_meta"
